/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home.index": [],
    "gardening.index": [],
    "gardening.gardens.index": [],
    "gardening.gardens.show": [
        {
            "name": "garden",
            "required": true,
            "binding": "uuid"
        }
    ],
    "gardening.gardens.store": [],
    "gardening.gardens.create": [],
    "gardening.plants.index": [],
    "gardening.plants.create": [],
    "gardening.plants.show": [
        {
            "name": "garden",
            "required": true
        }
    ],
    "gardening.plants.store": [],
    "auth.index": [],
    "auth.create": []
}
}
export {};
